### ISSUE TITLE
profile banner image

### ISSUE THREAD

**Issue by neb-b** [neb-b/daisy#25]

**Comment by bennyhodl** [comment]
picking this one up 👍

**Comment by neb-b** [comment]
@bennyhodl great! FYI I just created this https://github.com/neb-b/daisy/issues/34

This issue doesn't need to do that but just know it will use nostr.band in the future

**Comment by neb-b** [comment]
@bennyhodl are you still working on this? was hoping to get it in the next release and can pick it up if you don't plan to finish it soon

**Comment by neb-b** [comment]
got a little carried away with the profile UI changes and started working on this https://github.com/neb-b/daisy/pull/53. Sorry if you were almost ready with it.
